---
name: actionlint
permissions: {}
on:
  push:
    branches: [main]
    paths:
      - .github/**
  pull_request:
    branches: [main]
    paths:
      - .github/**
jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
      - uses: khulnasoftproj/khulnasoft-installer@v2.1.2 # v2.1.2
        with:
          khulnasoft_version: v2.6.0
      - run: actionlint
